# You can pull this image from https://cloud.docker.com/u/msaffarm/repository/docker/msaffarm/rasa_nlu

ARG BASE_IMAGE=jupyter/scipy-notebook
FROM $BASE_IMAGE

LABEL maintainer="Mansour Saffar M., msaffarmehrjardy@gmail.com"

USER $NB_UID

# install some of the NLP libraries
RUN conda install --quiet --yes \
    'nltk=3.3*' \
    'gensim=3.4*' \
    'spacy=2*' && \
    pip install rasa_nlu sentencepiece

# download dataset for the NLP libraries
RUN python -m spacy download en && \
    python -c "import nltk; nltk.download('popular', halt_on_error=False)"
    
# rasa nlu server port
EXPOSE 5000

USER $NB_UID
